import { DashboardData } from '../core/types';

export class GithubReporter {
  report(data: DashboardData): string {
    const { totals, healthScore } = data;
    const lines: string[] = [];

    const gradeEmoji: Record<string, string> = { A: ':star:', B: ':white_check_mark:', C: ':yellow_circle:', D: ':warning:', F: ':red_circle:' };

    lines.push('## QA Dashboard Report');
    lines.push('');
    lines.push(`**Health: ${gradeEmoji[healthScore.grade] || ''} Grade ${healthScore.grade}** (${(healthScore.score * 100).toFixed(0)}%)`);
    lines.push('');

    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| Total Tests | ${totals.total} |`);
    lines.push(`| Passed | ${totals.passed} |`);
    lines.push(`| Failed | ${totals.failed} |`);
    lines.push(`| Pass Rate | ${(totals.passRate * 100).toFixed(1)}% |`);
    lines.push(`| Frameworks | ${data.frameworks.length} |`);
    lines.push('');

    if (data.frameworks.length > 0) {
      lines.push('### Framework Breakdown');
      lines.push('');
      lines.push('| Framework | Tests | Passed | Failed | Pass Rate |');
      lines.push('|-----------|-------|--------|--------|-----------|');

      for (const fw of data.frameworks) {
        lines.push(`| ${fw.framework} | ${fw.total} | ${fw.passed} | ${fw.failed} | ${(fw.passRate * 100).toFixed(1)}% |`);
      }
      lines.push('');
    }

    const failures = data.tests.filter((t) => t.status === 'failed');
    if (failures.length > 0) {
      lines.push('<details>');
      lines.push(`<summary>Failed Tests (${failures.length})</summary>`);
      lines.push('');
      for (const t of failures.slice(0, 15)) {
        lines.push(`- **[${t.framework}]** ${t.name} — ${t.error?.substring(0, 80) || 'Failed'}`);
      }
      if (failures.length > 15) {
        lines.push(`- ... and ${failures.length - 15} more`);
      }
      lines.push('');
      lines.push('</details>');
    }

    lines.push('');
    lines.push('---');
    lines.push('*Generated by [qa-dash](https://github.com/mustafaautomation/qa-dash)*');

    return lines.join('\n');
  }
}
